Spring:
 datasource:
  url: jdbc:mysql://localhost:3306/film
  username: root
  password: 1234
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true 
    
